# 🦷 configuration for upload file
spring:
  jpa:
    hibernate:
      ddl-auto: update
# 🦷 configuration for connect database
  datasource:
    url: jdbc:postgresql://localhost:5432/backend
    username: postgres
    password: syspass
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 5MB
---
app :
  token :
    secret : m#MySecretGGWP2021
    issuer : FameServiceBackend